services:
  # Healthcheck web service
  - type: web
    name: sparkaph-health
    env: python
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python healthcheck.py
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080

  # Сервис пользовательского бота
  - type: worker
    name: sparkaph-user-bot
    env: python
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python start_user_bot.py
    plan: free
    envVars:
      - key: USER_BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: ADMIN_ID
        sync: false

  # Сервис админского бота
  - type: worker
    name: sparkaph-admin-bot
    env: python
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python start_admin_bot.py
    plan: free
    envVars:
      - key: ADMIN_BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: ADMIN_ID
        sync: false

  # Сервис бота инфлюенсеров
  - type: worker
    name: sparkaph-influencer-bot
    env: python
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python start_influencer_bot.py
    plan: free
    envVars:
      - key: INFLUENCER_BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: ADMIN_ID
        sync: false

  # Новые сервисы
  - type: web
    name: user-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python user_bot.py
    envVars:
      - key: USER_BOT_TOKEN
        sync: false

  - type: web
    name: admin-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python admin_bot.py
    envVars:
      - key: ADMIN_BOT_TOKEN
        sync: false

  - type: web
    name: influencer-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python influencer_bot.py
    envVars:
      - key: INFLUENCER_BOT_TOKEN
        sync: false

  - type: web
    name: sparkaph-bots
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_bots.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 